-- Run this in your Supabase SQL editor to create the monitors table

create table if not exists monitors (
  id bigint generated by default as identity primary key,
  url text not null,
  email text not null,
  last_hash text,
  created_at timestamptz not null default now()
);
